# Generated by Django 4.1.7 on 2023-05-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='answer_well_writte',
            new_name='answer_well_written',
        ),
    ]
