# Generated by Django 4.1.7 on 2023-05-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_answer_well_writte_score_answer_well_written'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='score',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='score',
            name='question_body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='score',
            name='question_title',
            field=models.TextField(default=''),
        ),
    ]
